### ISSUE TITLE
Block group IDs coming back as null for the 2013-2017 ACS

### ISSUE THREAD

**Issue by walkerke** [uscensusbureau/api#11]
Hi @loganpowell -

A tidycensus user just alerted me to an issue with block group IDs coming out of the 2013-2017 5-year ACS API over in https://github.com/walkerke/tidycensus/issues/347.  `block group` is returning `null` when requested from the API - [see here for an example](https://api.census.gov/data/2017/acs/acs5?get=NAME,B01001_001E&for=block%20group:*&in=state:01&in=county:*&in=tract:*).   I've run through a few states/counties to test this out and it is consistently missing.  This does not appear to be an issue for any other year.  Thanks for looking into this when you get the chance!

Kyle

**Comment by loganpowell** [comment]
Can you send this bug report to cedsci.feedback@census.gov and copy me: logan.t.powell@census.gov?

**Comment by walkerke** [comment]
@loganpowell - I note that this is now fixed.  Thanks!
