### ISSUE TITLE
Block group data prior to 2013?

### ISSUE THREAD

**Issue by walkerke** [uscensusbureau/api#13]
Hi @loganpowell -

I was fixing some bugs over in tidycensus today and I noticed that block group data appear to have been removed from the ACS APIs for the 2008-2012 5-year dataset and earlier.  Block group is also no longer listed as an available geography over on the website: https://api.census.gov/data/2012/acs/acs5/geography.html.  

Do you know if this is a temporary removal or is it permanent?  Thanks!

**Comment by loganpowell** [comment]
Jeez, I hadn't heard. I also saw your post on Slack. If the geography has been removed from the doc site, that is a sign that it's not temporary. But let's see how the convo evolves on Slack.

**Comment by walkerke** [comment]
Answered on Slack - BG data is not available via the API prior to 2009-2013.  Users in need of the data should instead download the raw summary files (the R package totalcensus helps with this) or they should use NHGIS.
