### ISSUE TITLE
Household serial numbers for 2018 PUMS API

### ISSUE THREAD

**Issue by walkerke** [uscensusbureau/api#3]
I know that the PUMS API is not "official" yet; however I did notice that Census is starting to advertise the data.census.gov Microdata tool (e.g. http://apdu.org/2020/05/27/new-microdata-access-tool-for-acs-and-cps/), which has the API as one of the output options.  Right now, household serial numbers for the 2018 ACS do not come through correctly, e.g. [at this example call to the API](https://api.census.gov/data/2018/acs/acs1/pums?get=SERIALNO%2CSPORDER%2CWGTP%2CPWGTP%2CAGEP%2CPUMA&ucgid=0400000US50): 

```
[["SERIALNO","SPORDER","WGTP","PWGTP","AGEP","PUMA","ST"],
["*","1","42","43","58","100","50"],
["*","4","43","16","14","200","50"],
["*","3","43","37","15","200","50"],
["*","2","43","23","42","200","50"],
["*","1","43","43","49","200","50"],
["*","2","58","34","10","300","50"],
...
```
It would be fantastic to get household serial numbers to come through the API for 2018 correctly as this would enable use of replicate weights, appropriate variance estimation in modeling, etc.  I haven't noticed this issue for earlier years.  Thanks for all your hard work on this, I appreciate it!

**Comment by walkerke** [comment]
Thank you for fixing this!  We've already implemented it in tidycensus.

**Comment by loganpowell** [comment]
Glad to hear it! Happy 4th to you and yours :)
